name: Static Analysis
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: nix-community
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: treefmt
        run: |
          export NIXPKGS_ALLOW_UNFREE=1
          nix develop --impure -c treefmt --ci
